import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"; // Allowing you to manage user authentication and sessions.
import { Toaster } from "sonner"; // Toaster for notifications.
import React from 'react';

export const metadata = {
  title: "Prepmania-AI Mock Interview",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Toaster /> {/* Toaster for notifications */}
          {children} {/* Render children */}
        </body>
      </html>
    </ClerkProvider>
  );
}
